config/routes.rb
Rails.application.routes.draw do
  resources :user_feedbacks

  root 'user_feedbacks#index'

end

app/models/user_feedback.rb
class UserFeedback < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_feedbacks_controller.rb
class UserFeedbacksController < ApplicationController
  before_action :set_user_feedback, only: [:show, :edit, :update, :destroy]

  # GET /user_feedbacks
  # GET /user_feedbacks.json
  def index
    @user_feedbacks = UserFeedback.all
  end

  # GET /user_feedbacks/1
  # GET /user_feedbacks/1.json
  def show
  end

  # GET /user_feedbacks/new
  def new
    @user_feedback = UserFeedback.new
  end

  # GET /user_feedbacks/1/edit
  def edit
  end

  # POST /user_feedbacks
  # POST /user_feedbacks.json
  def create
    @user_feedback = UserFeedback.new(user_feedback_params)

    respond_to do |format|
      if @user_feedback.save
        format.html { redirect_to @user_feedback, notice: 'User feedback was successfully created.' }
        format.json { render :show, status: :created, location: @user_feedback }
      else
        format.html { render :new }
        format.json { render json: @user_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_feedbacks/1
  # PATCH/PUT /user_feedbacks/1.json
  def update
    respond_to do |format|
      if @user_feedback.update(user_feedback_params)
        format.html { redirect_to @user_feedback, notice: 'User feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_feedback }
      else
        format.html { render :edit }
        format.json { render json: @user_feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_feedbacks/1
  # DELETE /user_feedbacks/1.json
  def destroy
    @user_feedback.destroy
    respond_to do |format|
      format.html { redirect_to user_feedbacks_url, notice: 'User feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_feedback
      @user_feedback = UserFeedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_feedback_params
      params.require(:user_feedback).permit(:email, :feedback)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_feedbacks_helper.rb
module UserFeedbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedbackApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_feedbacks/_form.html.erb
<%= form_for(@user_feedback) do |f| %>
  <% if @user_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_feedback.errors.count, "error") %> prohibited this user_feedback from being saved:</h2>

      <ul>
      <% @user_feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :feedback %><br>
    <%= f.text_field :feedback %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_feedbacks/edit.html.erb
<h1>Editing User Feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_feedback %> |
<%= link_to 'Back', user_feedbacks_path %>

app/views/user_feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Feedback</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_feedbacks.each do |user_feedback| %>
      <tr>
        <td><%= user_feedback.email %></td>
        <td><%= user_feedback.feedback %></td>
        <td><%= link_to 'Show', user_feedback %></td>
        <td><%= link_to 'Edit', edit_user_feedback_path(user_feedback) %></td>
        <td><%= link_to 'Destroy', user_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User feedback', new_user_feedback_path %>

app/views/user_feedbacks/new.html.erb
<h1>New User Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', user_feedbacks_path %>

app/views/user_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user_feedback.email %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @user_feedback.feedback %>
</p>

<%= link_to 'Edit', edit_user_feedback_path(@user_feedback) %> |
<%= link_to 'Back', user_feedbacks_path %>